### ISSUE TITLE
how to set path for openvidu.recording in docker

### ISSUE THREAD

**Issue by adyasasingh5** [OpenVidu/openvidu-recording-server-endpoint#1]
docker run -p 4443:4443 --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /PATH/TO/VIDEO/FILES:/PATH/TO/VIDEO/FILES \
    -e openvidu.recording=true \
    -e openvidu.recording.path=/PATH/TO/VIDEO/FILES \
openvidu/openvidu-server-kms:2.9.0

i M GETTING ERROR WHILE RUNNING

**Comment by pabloFuente** [comment]
Please, do not open the same issue on different repos https://github.com/OpenVidu/openvidu/issues/259
